### ISSUE TITLE
Cannot compile the package alongside ROS navigation package

### ISSUE THREAD

**Issue by Megacephalo** [spalanza/riskrrt_ros#1]
I would like to install the package from the repository, but I'd already installed the ROS official navigation package under my workspace. If I have RISK-RRT alongside Navigation and catkin_make them, there will be a series of conflicts such as the list below, clearly showing a series of conflicts involving 
planner
global_planner
navfn
costname_2d 
layers

---

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "navfn" to target "planner" which is not built
  in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "costmap_2d" to target "planner" which is not
  built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "layers" to target "planner" which is not built
  in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/liblaser_geometry.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libpcl_ros_filters.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libpcl_ros_io.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libpcl_ros_tf.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_common.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_common.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_kdtree.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_kdtree.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_octree.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_octree.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_search.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_search.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_surface.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_surface.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_sample_consensus.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_sample_consensus.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_filters.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_filters.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_features.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_features.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_segmentation.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_segmentation.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_io.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_io.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_registration.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_registration.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_keypoints.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_keypoints.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_recognition.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_recognition.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_visualization.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_visualization.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_people.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_people.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_outofcore.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_outofcore.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_tracking.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_tracking.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_apps.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libpcl_apps.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_iostreams.so" to target "planner" which
  is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_serialization.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libqhull.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libqhull.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libOpenNI.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libflann_cpp_s.a" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libflann_cpp_s.a" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libvtkCommon.so.5.8.0" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libvtkRendering.so.5.8.0" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libvtkHybrid.so.5.8.0" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libvtkCharts.so.5.8.0" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/indigo/lib/libdynamic_reconfigure_config_init_mutex.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libnodeletlib.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libbondcpp.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libuuid.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/librosbag.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/librosbag_storage.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_program_options.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libroslz4.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/liblz4.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libtopic_tools.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "voxel_grid" to target "planner" which is not
  built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libtinyxml.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libclass_loader.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/libPocoFoundation.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libdl.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libroslib.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libtf.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libtf2_ros.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libactionlib.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libmessage_filters.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libroscpp.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_signals.so"
  to target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_filesystem.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libxmlrpcpp.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libtf2.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/indigo/lib/libroscpp_serialization.so" to target "planner" which
  is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/librosconsole.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/librosconsole_log4cxx.so"
  to target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/indigo/lib/librosconsole_backend_interface.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/liblog4cxx.so" to target "planner"
  which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_regex.so"
  to target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/librostime.so" to target
  "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_date_time.so" to target "planner" which
  is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libcpp_common.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_system.so"
  to target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_thread.so"
  to target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libpthread.so" to
  target "planner" which is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:58 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libconsole_bridge.so" to target "planner" which
  is not built in this directory.

CMake Error at navigation/global_planner/CMakeLists.txt:63 (install):
  install TARGETS given target "planner" which does not exist in this
  directory.

---

But if I stash the navigation package out of the workspace, the 'costmap_2d' in the workspace's "include" directory will complain error messages as:

---

CMake Error at /home/iceira/indigo_ws/devel/share/costmap_2d/cmake/costmap_2dConfig.cmake:106 (message):
  Project 'costmap_2d' specifies
  '/home/iceira/indigo_ws/src/navigation/costmap_2d/include' as an include
  dir, which is not found.  It does neither exist as an absolute directory
  nor in
  '/home/iceira/indigo_ws/src/navigation/costmap_2d//home/iceira/indigo_ws/src/navigation/costmap_2d/include'.
  Ask the maintainer 'David V.  Lu!! davidvlu@gmail.com, Michael Ferguson
  mferguson@fetchrobotics.com' to fix it.

---

So, apart from uninstalling all the ROS navigation stack for testing RISK-RRT each time I want to use the latter package, is there a better way to have them both under the same workspace directory? Thanks in advance !!

**Comment by procopiostein** [comment]
I made a pull request to address this problem, please give us a feedback if that solves your problem.

**Comment by Megacephalo** [comment]
Dear Procopio,

Thank you! The new version resolved the mentioned problem. Except that the launch files could not launch the riskrrt planner node (maybe due to the old naming way in the default launch files. But the planner can be launched apart), everything is working accordingly. Have a great day !

**Comment by procopiostein** [comment]
Hi Megacephalo,
Thanks for your feedback.
Regarding the launch file, I had also changed the name there, so it should launch without problems. 
Did you updated your launch files as well?

**Comment by Megacephalo** [comment]
Dear Procopio,

Sorry for not replying sooner. I did update the package and everything works like a charm. Thank you so much! Hey, by the way, is this the only and latest package of Risk-RRT? Or there is somebody else working and improving this algorithm? If it is not convenient to release the rest of the codes, that's fine, I understand. Once again, thank you!

**Comment by procopiostein** [comment]
Hi,
Thanks for your feedback. 
Yes, this is the only and latest package of RiskRRT. Unfotunately it is not a very mature code, and there is still space for lots of improvements, but the core idea of the code is implemented. Let me know if you have some questions about it, or where to tinker in the case you are willing to improve it.
Cheers!
